In [ ]:
from google.colab import files
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os
import numpy as np
import pandas as pd
import datetime as dt

In [ ]:
train=pd.read_csv('/content/drive/MyDrive/날씨 빅콘/data/전처리데이터/train_test/ver_0728/train_파변추가.csv')
test=pd.read_csv('/content/drive/MyDrive/날씨 빅콘/data/전처리데이터/train_test/ver_0728/test_파변추가.csv')

In [ ]:
print('train shape :',train.shape)
print('test shape :',test.shape)

train shape : (49674, 170)
test shape : (12444, 169)

# 매월 1일 유무 binary 변수

In [ ]:
train.head()

,yyyymmdd,area,sex,frequency,dd_mes,sum_dpth_fhsc,dd_mefs,ssrate,ss_dur,sum_ss_hr,...,뇌졸중_약물치료,심장병_약물치료,고혈압_약물치료,이상지질혈증_약물치료,뇌졸중_가족력,심장병_가족력,고혈압_가족력,smoking,day_mean_smoke1,day_mean_smoke2
0,2012-01-01,강원,1,3.0,10.136053,2.155943,1.303480,35.856285,9.632506,3.444997,...,1432,4145,37595,3436,11696,5522,22179,86866,37878,1566.0
1,2012-01-01,강원,2,3.0,10.136053,2.155943,1.303480,35.856285,9.632506,3.444997,...,1135,3921,37876,6337,10338,4758,23802,4812,732,30.0
2,2012-01-01,경기,1,4.0,1.029764,0.085438,0.096118,25.748326,9.669065,2.485800,...,8446,21502,209877,25150,90075,52590,178493,632641,260886,9070.0
3,2012-01-01,경기,2,5.0,1.029764,0.085438,0.096118,25.748326,9.669065,2.485800,...,5947,15546,182918,35864,76109,46451,177494,46263,5653,183.0
4,2012-01-01,경남,1,2.0,0.865082,0.293056,0.533394,29.514334,9.814313,2.896959,...,2789,6884,56267,5476,24870,13712,42061,206829,90091,3604.0

In [ ]:
test.head()

,yyyymmdd,area,sex,dd_mes,sum_dpth_fhsc,dd_mefs,ssrate,ss_dur,sum_ss_hr,min_tg,...,뇌졸중_약물치료,심장병_약물치료,고혈압_약물치료,이상지질혈증_약물치료,뇌졸중_가족력,심장병_가족력,고혈압_가족력,smoking,day_mean_smoke1,day_mean_smoke2
0,2016-01-01,강원,1,25.262803,8.088057,6.832984,41.929419,9.633102,4.029989,-8.917460,...,2151,6583,52127,9121,14287,7722,31099,95349,36253,1200.0
1,2016-01-01,강원,2,25.262803,8.088057,6.832984,41.929419,9.633102,4.029989,-8.917460,...,1571,5149,49827,15369,13425,7290,34145,6318,795,20.0
2,2016-01-01,경기,1,3.140683,0.247502,0.263841,19.758979,9.668681,1.907674,-6.721469,...,12187,34825,320595,70860,114192,75843,262945,752923,269648,7402.0
3,2016-01-01,경기,2,3.140683,0.247502,0.263841,19.758979,9.668681,1.907674,-6.721469,...,8042,21768,261275,96956,105693,72481,284696,65555,6525,231.0
4,2016-01-01,경남,1,0.415067,0.216473,0.155119,86.066663,9.814577,8.444625,-6.450657,...,4059,10755,80255,14161,29888,18452,59062,223923,86310,2855.0

In [ ]:
train['day']=train['yyyymmdd'].str[8:10]
test['day']=test['yyyymmdd'].str[8:10]

In [ ]:
train.head(1)
test.head(1)

,yyyymmdd,area,sex,dd_mes,sum_dpth_fhsc,dd_mefs,ssrate,ss_dur,sum_ss_hr,min_tg,...,심장병_약물치료,고혈압_약물치료,이상지질혈증_약물치료,뇌졸중_가족력,심장병_가족력,고혈압_가족력,smoking,day_mean_smoke1,day_mean_smoke2,day
0,2016-01-01,강원,1,25.262803,8.088057,6.832984,41.929419,9.633102,4.029989,-8.91746,...,6583,52127,9121,14287,7722,31099,95349,36253,1200.0,01

In [ ]:
train['day1']=0

for i in range(train.shape[0]):
  if train['day'][i]=='01':
    train['day1'][i]=1
  else:
    train['day1'][i]=0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [ ]:
test['day1']=0

for i in range(test.shape[0]):
  if test['day'][i]=='01':
    test['day1'][i]=1
  else:
    test['day1'][i]=0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [ ]:
train.loc[train['day1']==1,'day'].unique()

array(['01'], dtype=object)

In [ ]:
train.loc[train['day1']!=1,'day'].unique()

array(['02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23',
       '24', '25', '26', '27', '28', '29', '30', '31'], dtype=object)

In [ ]:
test.loc[test['day1']==1,'day'].unique()

array(['01'], dtype=object)

In [ ]:
test.loc[test['day1']!=1,'day'].unique()

array(['02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23',
       '24', '25', '26', '27', '28', '29', '30', '31'], dtype=object)

In [ ]:
print('train shape :',train.shape)
print('test shape :',test.shape)

train shape : (49674, 172)
test shape : (12444, 171)

In [ ]:
train.isna().sum().sum()
test.isna().sum().sum()

0

In [ ]:
train.drop(['day'],axis=1,inplace=True)
train.head()

,yyyymmdd,area,sex,frequency,dd_mes,sum_dpth_fhsc,dd_mefs,ssrate,ss_dur,sum_ss_hr,...,심장병_약물치료,고혈압_약물치료,이상지질혈증_약물치료,뇌졸중_가족력,심장병_가족력,고혈압_가족력,smoking,day_mean_smoke1,day_mean_smoke2,day1
0,2012-01-01,강원,1,3.0,10.136053,2.155943,1.303480,35.856285,9.632506,3.444997,...,4145,37595,3436,11696,5522,22179,86866,37878,1566.0,1
1,2012-01-01,강원,2,3.0,10.136053,2.155943,1.303480,35.856285,9.632506,3.444997,...,3921,37876,6337,10338,4758,23802,4812,732,30.0,1
2,2012-01-01,경기,1,4.0,1.029764,0.085438,0.096118,25.748326,9.669065,2.485800,...,21502,209877,25150,90075,52590,178493,632641,260886,9070.0,1
3,2012-01-01,경기,2,5.0,1.029764,0.085438,0.096118,25.748326,9.669065,2.485800,...,15546,182918,35864,76109,46451,177494,46263,5653,183.0,1
4,2012-01-01,경남,1,2.0,0.865082,0.293056,0.533394,29.514334,9.814313,2.896959,...,6884,56267,5476,24870,13712,42061,206829,90091,3604.0,1

In [ ]:
test.drop(['day'],axis=1,inplace=True)
test.head()

,yyyymmdd,area,sex,dd_mes,sum_dpth_fhsc,dd_mefs,ssrate,ss_dur,sum_ss_hr,min_tg,...,심장병_약물치료,고혈압_약물치료,이상지질혈증_약물치료,뇌졸중_가족력,심장병_가족력,고혈압_가족력,smoking,day_mean_smoke1,day_mean_smoke2,day1
0,2016-01-01,강원,1,25.262803,8.088057,6.832984,41.929419,9.633102,4.029989,-8.917460,...,6583,52127,9121,14287,7722,31099,95349,36253,1200.0,1
1,2016-01-01,강원,2,25.262803,8.088057,6.832984,41.929419,9.633102,4.029989,-8.917460,...,5149,49827,15369,13425,7290,34145,6318,795,20.0,1
2,2016-01-01,경기,1,3.140683,0.247502,0.263841,19.758979,9.668681,1.907674,-6.721469,...,34825,320595,70860,114192,75843,262945,752923,269648,7402.0,1
3,2016-01-01,경기,2,3.140683,0.247502,0.263841,19.758979,9.668681,1.907674,-6.721469,...,21768,261275,96956,105693,72481,284696,65555,6525,231.0,1
4,2016-01-01,경남,1,0.415067,0.216473,0.155119,86.066663,9.814577,8.444625,-6.450657,...,10755,80255,14161,29888,18452,59062,223923,86310,2855.0,1

In [ ]:
print('train shape :',train.shape)
print('test shape :',test.shape)

train shape : (49674, 171)
test shape : (12444, 170)

In [ ]:
train.isna().sum().sum()
test.isna().sum().sum()

0

In [ ]:
train.to_csv('/content/drive/MyDrive/날씨 빅콘/data/전처리데이터/train_test/ver_0729/train_0729.csv',index=False)
test.to_csv('/content/drive/MyDrive/날씨 빅콘/data/전처리데이터/train_test/ver_0729/test_0729.csv',index=False)