In [ ]:
from google.colab import files
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
import numpy as np
import pandas as pd
import datetime as dt

### airkorea 인구 가중치 생성

In [ ]:
# airkorea data
data = pd.read_csv("/content/drive/MyDrive/날씨 빅콘/data/전처리데이터/대기오염/air_mice.csv")

# 인구 data
pop = pd.read_csv('/content/drive/MyDrive/날씨 빅콘/data/인구수/총인구수_air.csv')

In [ ]:
pop0 = pop.copy()
pop0.loc[244, "시군구"] = "세종"
pop0 = pop0.dropna(subset=["시군구"]).reset_index(drop=True)

In [ ]:
pd.set_option('display.max_rows', None)

In [ ]:
data['측정일']=data['측정일'].astype(str)
data['year']= data['측정일'].str[:4]

In [ ]:
con1 = data['시군구']!='강서로45다길'
data2 = data[con1]

con2 = data2['시군구']!='중구광복로'
data2 = data2[con2]

con3 = data2['시군구']!='강서로'
data2 = data2[con3]

In [ ]:
data2 = data2.reset_index(drop=True)

In [ ]:
data2.to_csv("/content/drive/MyDrive/날씨 빅콘/data/전처리데이터/대기오염/air_mice2.csv", index=False)

In [ ]:
df1 = data2[data2['year']=='2011']
df2 = data2[data2['year']=='2012']
df3 = data2[data2['year']=='2013']
df4 = data2[data2['year']=='2014']
df5 = data2[data2['year']=='2015']
df6 = data2[data2['year']=='2016']

df1 = df1[["지역","시군구"]]
df1.drop_duplicates(["지역","시군구"], keep = 'first', inplace=True)
df1= df1.reset_index(drop=True)

df2 = df2[["지역","시군구"]]
df2.drop_duplicates(["지역","시군구"], keep = 'first', inplace=True)
df2= df2.reset_index(drop=True)

df3 = df3[["지역","시군구"]]
df3.drop_duplicates(["지역","시군구"], keep = 'first', inplace=True)
df3= df3.reset_index(drop=True)

df4 = df4[["지역","시군구"]]
df4.drop_duplicates(["지역","시군구"], keep = 'first', inplace=True)
df4= df4.reset_index(drop=True)

df5 = df5[["지역","시군구"]]
df5.drop_duplicates(["지역","시군구"], keep = 'first', inplace=True)
df5= df5.reset_index(drop=True)

df6 = df6[["지역","시군구"]]
df6.drop_duplicates(["지역","시군구"], keep = 'first', inplace=True)
df6= df6.reset_index(drop=True)

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [ ]:
weight1 = pd.merge(df1, pop0[["지역","시군구","pop11"]], how = "left", on=["지역","시군구"])
weight2 = pd.merge(df2, pop0[["지역","시군구","pop12"]], how = "left", on=["지역","시군구"])
weight3 = pd.merge(df3, pop0[["지역","시군구","pop13"]], how = "left", on=["지역","시군구"])
weight4 = pd.merge(df4, pop0[["지역","시군구","pop14"]], how = "left", on=["지역","시군구"])
weight5 = pd.merge(df5, pop0[["지역","시군구","pop15"]], how = "left", on=["지역","시군구"])
weight6 = pd.merge(df6, pop0[["지역","시군구","pop16"]], how = "left", on=["지역","시군구"])

In [ ]:
weight1.loc[weight1['pop11'].isnull(), '시군구'].unique()

array([], dtype=object)

In [ ]:
weight2.loc[weight2['pop12'].isnull(), '시군구'].unique()

array([], dtype=object)

In [ ]:
weight3.loc[weight3['pop13'].isnull(), '시군구'].unique()

array([], dtype=object)

In [ ]:
weight4.loc[weight4['pop14'].isnull(), '시군구'].unique()

array([], dtype=object)

In [ ]:
weight5.loc[weight5['pop15'].isnull(), '시군구'].unique()

array([], dtype=object)

In [ ]:
weight6.loc[weight6['pop16'].isnull(), '시군구'].unique()

array([], dtype=object)

In [ ]:
weight = pd.merge(weight1, weight2, how="outer", on=["지역","시군구"])
weight = pd.merge(weight, weight3, how="outer", on=["지역","시군구"])
weight = pd.merge(weight, weight4, how="outer", on=["지역","시군구"])
weight = pd.merge(weight, weight5, how="outer", on=["지역","시군구"])
weight = pd.merge(weight, weight6, how="outer", on=["지역","시군구"])

In [ ]:
weight.head()

   지역  시군구     pop11     pop12     pop13     pop14     pop15     pop16
0  강원  강릉시  217571.0  217741.0  216806.0  215807.0  214560.0  213846.0
1  강원  고성군   30057.0   30124.0   30398.0   30269.0   30060.0   30114.0
2  강원  동해시   95804.0   93897.0   95143.0   94562.0   93895.0   93297.0
3  강원  삼척시   72312.0   72463.0   73023.0   72314.0   70839.0   69599.0
4  강원  양구군   22285.0   22799.0   23594.0   23888.0   24089.0   24010.0

In [ ]:
pop1 = weight.groupby('지역').sum().reset_index()

In [ ]:
pop1

    지역       pop11       pop12       pop13       pop14       pop15       pop16
0   강원   1115911.0   1118803.0   1123178.0   1124721.0   1129409.0   1134261.0
1   경기  11937415.0  12093299.0  12234630.0  12357830.0  12522606.0  12716780.0
2   경남   2550756.0   2563358.0   2694698.0   2712157.0   2729417.0   2742130.0
3   경북   1827974.0   2073435.0   2074836.0   2075875.0   2079717.0   2078044.0
4   광주   1463464.0   1469216.0   1472910.0   1475884.0   1472199.0   1469214.0
5   대구   2507271.0   2505644.0   2501588.0   2493264.0   2487829.0   2484557.0
6   대전   1515603.0   1524583.0   1532811.0   1531809.0   1518775.0   1514370.0
7   부산   3427245.0   3417656.0   3527635.0   3519401.0   3467961.0   3498529.0
8   서울  10249679.0  10195318.0  10143645.0  10103233.0  10022181.0   9930616.0
9   세종         0.0    113117.0    122153.0    156125.0    210884.0    243048.0
10  울산   1135494.0   1147256.0   1156480.0   1166377.0   1173534.0   1172304.0
11  인천   2801274.0   2843981.0   2879782.0   2902608.0   2925815.0   2943069.0
12  전남   1089671.0   1090300.0   1086481.0   1084918.0   1084887.0   1083203.0
13  전북   1530132.0   1530461.0   1529989.0   1527974.0   1669460.0   1664716.0
14  제주    576156.0    583713.0    593806.0    607346.0    624395.0    641597.0
15  충남   1345103.0   1360743.0   1382399.0   1398950.0   1413479.0   1432133.0
16  충북   1076996.0   1081786.0   1087453.0   1246152.0   1245511.0   1319490.0

In [ ]:
weight.shape

(163, 8)

In [ ]:
s1 = []
s2 = []
s3 = []
s4 = []
s5 = []
s6 = []

for i in range(163):
  area = weight['지역'][i]
  s1.append(pop1.loc[pop1['지역']==area, "pop11"].values[0])
  s2.append(pop1.loc[pop1['지역']==area, "pop12"].values[0])
  s3.append(pop1.loc[pop1['지역']==area, "pop13"].values[0])
  s4.append(pop1.loc[pop1['지역']==area, "pop14"].values[0])
  s5.append(pop1.loc[pop1['지역']==area, "pop15"].values[0])
  s6.append(pop1.loc[pop1['지역']==area, "pop16"].values[0])

weight['pop_sum11'] = s1
weight['pop_sum12'] = s2
weight['pop_sum13'] = s3
weight['pop_sum14'] = s4
weight['pop_sum15'] = s5
weight['pop_sum16'] = s6

weight['weight11'] = weight['pop11']/weight['pop_sum11']
weight['weight12'] = weight['pop12']/weight['pop_sum12']
weight['weight13'] = weight['pop13']/weight['pop_sum13']
weight['weight14'] = weight['pop14']/weight['pop_sum14']
weight['weight15'] = weight['pop15']/weight['pop_sum15']
weight['weight16'] = weight['pop16']/weight['pop_sum16']

In [ ]:
weight = weight[['지역','시군구','weight11', 'weight12', 'weight13', 'weight14', 'weight15','weight16']]

In [ ]:
weight.head()

   지역  시군구  weight11  weight12  weight13  weight14  weight15  weight16
0  강원  강릉시  0.194972  0.194620  0.193029  0.191876  0.189975  0.188533
1  강원  고성군  0.026935  0.026925  0.027064  0.026912  0.026616  0.026549
2  강원  동해시  0.085853  0.083926  0.084709  0.084076  0.083136  0.082254
3  강원  삼척시  0.064801  0.064768  0.065015  0.064295  0.062722  0.061361
4  강원  양구군  0.019970  0.020378  0.021006  0.021239  0.021329  0.021168

In [ ]:
weight.to_csv('/content/drive/MyDrive/날씨 빅콘/data/인구수/weight_air.csv', index = False)