In [1]:
# 구글 드라이브 
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [24]:
import pandas as pd
import numpy as np
import datetime as dt

In [31]:
dj_mice = pd.read_csv('/content/drive/MyDrive/날씨 빅콘/data/전처리데이터/대기오염/대기오염mice/대전_대기오염_mice.csv')
cn_mice = pd.read_csv('/content/drive/MyDrive/날씨 빅콘/data/전처리데이터/대기오염/대기오염mice/충남_대기오염_mice.csv')
cb_mice = pd.read_csv('/content/drive/MyDrive/날씨 빅콘/data/전처리데이터/대기오염/대기오염mice/충북_대기오염_mice.csv')

In [32]:
dj_mice2 = dj_mice.loc[dj_mice['측정일']>=20120101,:]
dj_mice2

       지역       측정일  시군구       SO2        CO        O3       NO2       PM10
1825   대전  20120101  대덕구  0.006979  0.745833  0.014917  0.015292  59.145833
1826   대전  20120101   동구  0.011750  0.704167  0.010125  0.026083  62.833333
1827   대전  20120101   서구  0.006028  0.612500  0.014222  0.019403  38.236111
1828   대전  20120101  유성구  0.007042  0.587500  0.012125  0.021354  61.770833
1829   대전  20120101   중구  0.007729  0.833333  0.010625  0.024375  51.791667
...    ..       ...  ...       ...       ...       ...       ...        ...
10955  대전  20161231  대덕구  0.003646  0.625000  0.003646  0.032813  48.765957
10956  대전  20161231   동구  0.007958  0.966667  0.003375  0.037375  44.625000
10957  대전  20161231   서구  0.002569  0.552778  0.007639  0.022542  32.347222
10958  대전  20161231  유성구  0.003750  0.691667  0.005271  0.028438  48.829787
10959  대전  20161231   중구  0.005333  0.802083  0.003375  0.036562  49.166667

[9135 rows x 8 columns]

In [33]:
cn_mice['시군구'].unique()

array(['공주시', '당진시', '서산시', '아산시', '천안시', '태안군'], dtype=object)

In [34]:
cn_mice2 = cn_mice.loc[((cn_mice['시군구']=='공주시')|(cn_mice['시군구']=='아산시')|(cn_mice['시군구']=='천안시')) & (cn_mice['측정일']>=20120101),:]
cn_mice2.head()

      지역       측정일  시군구       SO2        CO        O3       NO2       PM10
2190  충남  20120101  공주시  0.007283  0.729167  0.026125  0.011308  82.086957
2193  충남  20120101  아산시  0.006125  0.904167  0.012208  0.026417  60.416667
2194  충남  20120101  천안시  0.009236  0.843056  0.012222  0.023833  74.416667
2196  충남  20120102  공주시  0.008458  0.808333  0.030458  0.009050  85.826087
2199  충남  20120102  아산시  0.007500  0.983333  0.009500  0.030625  80.916667

In [35]:
cb_mice2 = cb_mice.loc[(cb_mice['시군구'] == '청주시') & (cb_mice['측정일']>=20120101),:]
cb_mice2.head()

      지역       측정일  시군구       SO2        CO        O3       NO2        PM10
1557  충북  20120101  청주시  0.007500  0.815278  0.011660  0.026854   92.027778
1562  충북  20120102  청주시  0.008868  0.995833  0.010375  0.031917  105.542254
1567  충북  20120103  청주시  0.006897  0.963235  0.009875  0.034243  101.816000
1572  충북  20120104  청주시  0.009851  0.609220  0.016922  0.024858   80.576389
1577  충북  20120105  청주시  0.006924  0.627083  0.013042  0.031410   59.447761

In [36]:
df_list = [dj_mice2, cn_mice2, cb_mice2]

df1 = pd.concat(df_list, axis=0, ignore_index=True)
df1

       지역       측정일  시군구       SO2        CO        O3       NO2       PM10
0      대전  20120101  대덕구  0.006979  0.745833  0.014917  0.015292  59.145833
1      대전  20120101   동구  0.011750  0.704167  0.010125  0.026083  62.833333
2      대전  20120101   서구  0.006028  0.612500  0.014222  0.019403  38.236111
3      대전  20120101  유성구  0.007042  0.587500  0.012125  0.021354  61.770833
4      대전  20120101   중구  0.007729  0.833333  0.010625  0.024375  51.791667
...    ..       ...  ...       ...       ...       ...       ...        ...
16438  충북  20161227  청주시  0.003778  0.435417  0.017278  0.016785  37.458333
16439  충북  20161228  청주시  0.005168  0.544755  0.006909  0.030315  47.992806
16440  충북  20161229  청주시  0.004278  0.493056  0.011528  0.022597  37.321678
16441  충북  20161230  청주시  0.004368  0.629861  0.008167  0.027222  41.472222
16442  충북  20161231  청주시  0.004410  0.803472  0.004292  0.026611  54.335664

[16443 rows x 8 columns]

In [37]:
df2 = df1.groupby('측정일',as_index=False).mean()[['측정일', 'SO2', 'CO', 'O3', 'NO2', 'PM10']]
df2['지역'] = '세종'
df2 = df2[['지역', '측정일', 'SO2', 'CO', 'O3', 'NO2', 'PM10']]
df2

      지역       측정일       SO2        CO        O3       NO2       PM10
0     세종  20120101  0.007741  0.752778  0.013803  0.021658  64.747316
1     세종  20120102  0.008716  0.932818  0.012088  0.025666  82.466659
2     세종  20120103  0.007033  0.862229  0.012658  0.026456  72.720637
3     세종  20120104  0.009382  0.574404  0.021521  0.017221  60.174383
4     세종  20120105  0.006846  0.606258  0.015977  0.024962  47.273752
...   ..       ...       ...       ...       ...       ...        ...
1822  세종  20161227  0.003530  0.444059  0.022270  0.015690  36.792438
1823  세종  20161228  0.004347  0.599726  0.009243  0.028627  47.539022
1824  세종  20161229  0.003812  0.528395  0.014408  0.021882  36.889088
1825  세종  20161230  0.003958  0.663349  0.009385  0.028015  38.450617
1826  세종  20161231  0.003867  0.720525  0.006025  0.028750  46.816453

[1827 rows x 7 columns]

In [38]:
df2.to_csv('/content/drive/MyDrive/날씨 빅콘/data/전처리데이터/대기오염/대기오염mice/세종_대기오염_mice.csv', index=False)