In [ ]:
from google.colab import files
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os
import numpy as np
import pandas as pd
import datetime as dt

# 예보데이터

In [ ]:
dat= pd.read_csv('/content/drive/MyDrive/날씨 빅콘/data/전처리데이터/예보데이터/예보데이터_시도/예보_total.csv')

In [ ]:
dat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31059 entries, 0 to 31058
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         31059 non-null  object
 1   rainfall_24  31059 non-null  float64
 2   snow_24      31059 non-null  float64
 3   temp_24      31059 non-null  float64
 4   temp_48      31059 non-null  float64
 5   humid_24     31059 non-null  float64
 6   humid_48     31059 non-null  float64
 7   max_temp_24  31059 non-null  float64
 8   min_temp_24  31059 non-null  float64
 9   wind_24      31059 non-null  float64
 10  wind_48      31059 non-null  float64
 11  area         31059 non-null  object
dtypes: float64(10), object(2)
memory usage: 2.8+ MB

In [ ]:
dat['area'].unique()

array(['경기', '강원', '경남', '경북', '광주', '대구', '대전',
       '부산', '서울', '세종', '울산', '인천', '전남', '전북',
       '제주', '충남', '충북'], dtype=object)

In [ ]:
dat['rainfall_24_shift'] = dat.groupby('area')['rainfall_24'].shift(1)
dat['snow_24_shift'] = dat.groupby('area')['snow_24'].shift(1)
dat['temp_24_shift'] = dat.groupby('area')['temp_24'].shift(1)
dat['temp_48_shift'] = dat.groupby('area')['temp_48'].shift(2)
dat['humid_24_shift'] = dat.groupby('area')['humid_24'].shift(1)
dat['humid_48_shift'] = dat.groupby('area')['humid_48'].shift(2)
dat['max_temp_24_shift'] = dat.groupby('area')['max_temp_24'].shift(1)
dat['min_temp_24_shift'] = dat.groupby('area')['min_temp_24'].shift(1)
dat['wind_24_shift'] = dat.groupby('area')['wind_24'].shift(1)
dat['wind_48_shift'] = dat.groupby('area')['wind_48'].shift(2)

In [ ]:
dat.loc[dat['area']=='충북']

,date,rainfall_24,snow_24,temp_24,temp_48,humid_24,humid_48,max_temp_24,min_temp_24,wind_24,...,rainfall_24_shift,snow_24_shift,temp_24_shift,temp_48_shift,humid_24_shift,humid_48_shift,max_temp_24_shift,min_temp_24_shift,wind_24_shift,wind_48_shift
29232,2012-01-01,0.000000,0.00000,-4.500245,-2.210593,61.876663,69.763010,1.580959,-10.000696,1.028785,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29233,2012-01-02,0.000000,0.00000,-3.040538,-4.718354,65.230078,54.178071,0.867548,-8.012245,1.882576,...,0.000000,0.000000,-4.500245,NaN,61.876663,NaN,1.580959,-10.000696,1.028785,NaN
29234,2012-01-03,0.084070,0.08407,-4.989342,-4.749129,56.413137,57.971786,-0.481692,-9.737698,2.311564,...,0.000000,0.000000,-3.040538,-2.210593,65.230078,69.763010,0.867548,-8.012245,1.882576,1.369815
29235,2012-01-04,0.000000,0.00000,-5.764636,-3.197438,65.693232,66.784482,1.649739,-10.385940,1.409416,...,0.084070,0.084070,-4.989342,-4.718354,56.413137,54.178071,-0.481692,-9.737698,2.311564,2.307398
29236,2012-01-05,0.000000,0.00000,-4.446107,-4.173798,56.153130,53.887383,1.913419,-9.702390,1.486490,...,0.000000,0.000000,-5.764636,-4.749129,65.693232,57.971786,1.649739,-10.385940,1.409416,1.470581
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31054,2016-12-27,0.000000,0.00000,-3.043302,-2.280123,61.686415,55.260896,2.980986,-9.238554,1.219819,...,4.260315,4.260315,-0.717488,-0.309811,60.465726,58.657520,2.841214,-8.950949,2.643637,2.336611
31055,2016-12-28,2.451268,1.00000,-2.490160,-2.711737,57.345951,62.100412,5.080213,-8.585183,2.527701,...,0.000000,0.000000,-3.043302,-3.077123,61.686415,58.753971,2.980986,-9.238554,1.219819,1.268083
31056,2016-12-29,0.000000,0.00000,-2.923333,-0.078596,61.458769,72.320452,7.544815,-8.325949,1.274333,...,2.451268,1.000000,-2.490160,-2.280123,57.345951,55.260896,5.080213,-8.585183,2.527701,1.906050
31057,2016-12-30,0.000000,0.00000,-0.160768,1.703067,74.498600,74.930718,8.923348,-4.164205,1.359781,...,0.000000,0.000000,-2.923333,-2.711737,61.458769,62.100412,7.544815,-8.325949,1.274333,1.404732
31058,2016-12-31,0.000000,0.00000,2.183118,3.810940,74.747486,71.415485,9.332726,-2.047622,1.232250,...,0.000000,0.000000,-0.160768,-0.078596,74.498600,72.320452,8.923348,-4.164205,1.359781,1.365425

In [ ]:
dat.shape

(31059, 22)

In [ ]:
dat2=dat.fillna(method='bfill')

In [ ]:
dat2.loc[dat2['area']=='강원']

,date,rainfall_24,snow_24,temp_24,temp_48,humid_24,humid_48,max_temp_24,min_temp_24,wind_24,...,rainfall_24_shift,snow_24_shift,temp_24_shift,temp_48_shift,humid_24_shift,humid_48_shift,max_temp_24_shift,min_temp_24_shift,wind_24_shift,wind_48_shift
1827,2012-01-01,14.005090,11.402662,-2.769171,-2.780795,62.145093,54.361839,2.777686,-6.639387,2.430259,...,14.005090,11.402662,-2.769171,-2.780795,62.145093,54.361839,2.777686,-6.639387,2.430259,2.303822
1828,2012-01-02,0.000000,0.000000,-3.436881,-4.981487,57.343033,50.391861,2.012825,-8.660641,2.322310,...,14.005090,11.402662,-2.769171,-2.780795,62.145093,54.361839,2.777686,-6.639387,2.430259,2.303822
1829,2012-01-03,0.000000,0.000000,-5.245202,-4.448358,50.936193,48.045254,1.461069,-9.692602,2.474572,...,0.000000,0.000000,-3.436881,-2.780795,57.343033,54.361839,2.012825,-8.660641,2.322310,2.303822
1830,2012-01-04,0.000000,0.000000,-4.770948,-2.929077,47.270969,52.102991,2.996645,-9.952155,2.444897,...,0.000000,0.000000,-5.245202,-4.981487,50.936193,50.391861,1.461069,-9.692602,2.474572,2.354607
1831,2012-01-05,0.000000,0.000000,-4.640206,-4.164633,50.291953,51.382678,3.156663,-8.234346,2.130263,...,0.000000,0.000000,-4.770948,-4.448358,47.270969,48.045254,2.996645,-9.952155,2.444897,1.789684
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3649,2016-12-27,0.000000,0.000000,-2.565235,-2.524632,61.172195,48.004728,3.238003,-7.175128,1.759127,...,19.058887,11.114566,-0.320303,-0.108154,79.145687,81.782621,3.222180,-6.522826,2.460641,2.457015
3650,2016-12-28,2.203285,2.898609,-2.488572,-2.618673,48.936706,56.564923,5.470375,-8.930413,2.530485,...,0.000000,0.000000,-2.565235,-1.813777,61.172195,59.306309,3.238003,-7.175128,1.759127,2.077639
3651,2016-12-29,0.000000,0.000000,-2.089564,0.611746,52.047917,62.593095,6.787654,-8.490732,2.326736,...,2.203285,2.898609,-2.488572,-2.524632,48.936706,48.004728,5.470375,-8.930413,2.530485,2.271527
3652,2016-12-30,0.000000,0.000000,0.768342,2.565580,64.873902,63.724509,8.514550,-2.580655,1.983152,...,0.000000,0.000000,-2.089564,-2.618673,52.047917,56.564923,6.787654,-8.490732,2.326736,2.128928
3653,2016-12-31,0.000000,0.000000,2.438286,4.121406,66.459008,64.870635,9.147818,-1.725296,1.968750,...,0.000000,0.000000,0.768342,0.611746,64.873902,62.593095,8.514550,-2.580655,1.983152,2.245868

In [ ]:
dat2.isna().sum()

date                 0
rainfall_24          0
snow_24              0
temp_24              0
temp_48              0
humid_24             0
humid_48             0
max_temp_24          0
min_temp_24          0
wind_24              0
wind_48              0
area                 0
rainfall_24_shift    0
snow_24_shift        0
temp_24_shift        0
temp_48_shift        0
humid_24_shift       0
humid_48_shift       0
max_temp_24_shift    0
min_temp_24_shift    0
wind_24_shift        0
wind_48_shift        0
dtype: int64

In [ ]:
dat2.to_csv('/content/drive/MyDrive/날씨 빅콘/data/전처리데이터/예보데이터/예보데이터_시도/예보_tota_변수추가.csv')

# 지수데이터

In [ ]:
dat = pd.read_csv('/content/drive/MyDrive/날씨 빅콘/data/전처리데이터/지수데이터/grouped_A03_A07_D02_weighted_notnull.csv', index_col=0)

# 열이름 변경
dat.rename(columns={'tm_fc_ymd': 'yyyymmdd'}, inplace=True)

dat.head()

,yyyymmdd,area,A03_t1_max_weighted_mean,A03_t1_min_weighted_mean,A03_t1_mean_weighted_mean,A03_t1_range_weighted_mean,A03_t1_iqr_weighted_mean,A03_t2_max_weighted_mean,A03_t2_min_weighted_mean,A03_t2_mean_weighted_mean,...,D02_t1_median_weighted_mean,D02_t1_range_weighted_mean,D02_t2_max_weighted_mean,D02_t2_min_weighted_mean,D02_t2_median_weighted_mean,D02_t2_range_weighted_mean,D02_t3_max_weighted_mean,D02_t3_min_weighted_mean,D02_t3_median_weighted_mean,D02_t3_range_weighted_mean
0,2011-01-01,강원,-3.810937,-16.261543,-9.389451,12.450606,6.656067,-3.768142,-14.683870,-8.902063,...,0.032722,0.0,0.032722,0.032722,0.032722,0.0,0.032722,0.032722,0.032722,0.0
1,2011-01-01,경기,-3.856147,-16.497977,-9.602984,12.641830,7.433769,-3.674758,-15.711398,-9.316136,...,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0
2,2011-01-01,경남,-0.034429,-11.374359,-4.884414,11.339931,5.799530,0.033018,-11.390231,-4.486237,...,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0
3,2011-01-01,경북,-3.331246,-12.706639,-7.903421,9.375393,5.922338,-3.522688,-12.039500,-7.370034,...,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0
4,2011-01-01,광주,-3.499618,-9.155950,-6.311515,5.656332,2.862099,-2.603142,-10.230104,-6.160321,...,0.030374,0.0,0.030374,0.030374,0.030374,0.0,0.030374,0.030374,0.030374,0.0

In [ ]:
dat.columns

Index(['yyyymmdd', 'area', 'A03_t1_max_weighted_mean',
       'A03_t1_min_weighted_mean', 'A03_t1_mean_weighted_mean',
       'A03_t1_range_weighted_mean', 'A03_t1_iqr_weighted_mean',
       'A03_t2_max_weighted_mean', 'A03_t2_min_weighted_mean',
       'A03_t2_mean_weighted_mean', 'A03_t2_range_weighted_mean',
       'A03_t2_iqr_weighted_mean', 'A03_t3_max_weighted_mean',
       'A03_t3_min_weighted_mean', 'A03_t3_mean_weighted_mean',
       'A03_t3_range_weighted_mean', 'A03_t3_iqr_weighted_mean',
       'A07_max_weighted_mean', 'A07_min_weighted_mean',
       'A07_mean_weighted_mean', 'A07_range_weighted_mean',
       'A07_iqr_weighted_mean', 'D02_t1_max_weighted_mean',
       'D02_t1_min_weighted_mean', 'D02_t1_median_weighted_mean',
       'D02_t1_range_weighted_mean', 'D02_t2_max_weighted_mean',
       'D02_t2_min_weighted_mean', 'D02_t2_median_weighted_mean',
       'D02_t2_range_weighted_mean', 'D02_t3_max_weighted_mean',
       'D02_t3_min_weighted_mean', 'D02_t3_median_weighted_mean',
       'D02_t3_range_weighted_mean'],
      dtype='object')

In [ ]:
dat.shape

(37043, 34)

In [ ]:
dat2 = dat.copy()

In [ ]:
for col in dat2.columns[2:] :
  dat2[col+'_shift'] = dat2.groupby('area')[col].shift(1)

In [ ]:
dat2.shape

(37043, 66)

In [ ]:
dat2.head()

,yyyymmdd,area,A03_t1_max_weighted_mean,A03_t1_min_weighted_mean,A03_t1_mean_weighted_mean,A03_t1_range_weighted_mean,A03_t1_iqr_weighted_mean,A03_t2_max_weighted_mean,A03_t2_min_weighted_mean,A03_t2_mean_weighted_mean,...,D02_t1_median_weighted_mean_shift,D02_t1_range_weighted_mean_shift,D02_t2_max_weighted_mean_shift,D02_t2_min_weighted_mean_shift,D02_t2_median_weighted_mean_shift,D02_t2_range_weighted_mean_shift,D02_t3_max_weighted_mean_shift,D02_t3_min_weighted_mean_shift,D02_t3_median_weighted_mean_shift,D02_t3_range_weighted_mean_shift
0,2011-01-01,강원,-3.810937,-16.261543,-9.389451,12.450606,6.656067,-3.768142,-14.683870,-8.902063,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2011-01-01,경기,-3.856147,-16.497977,-9.602984,12.641830,7.433769,-3.674758,-15.711398,-9.316136,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2011-01-01,경남,-0.034429,-11.374359,-4.884414,11.339931,5.799530,0.033018,-11.390231,-4.486237,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2011-01-01,경북,-3.331246,-12.706639,-7.903421,9.375393,5.922338,-3.522688,-12.039500,-7.370034,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2011-01-01,광주,-3.499618,-9.155950,-6.311515,5.656332,2.862099,-2.603142,-10.230104,-6.160321,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
dat2.loc[dat2['area'] == '강원', :]

,yyyymmdd,area,A03_t1_max_weighted_mean,A03_t1_min_weighted_mean,A03_t1_mean_weighted_mean,A03_t1_range_weighted_mean,A03_t1_iqr_weighted_mean,A03_t2_max_weighted_mean,A03_t2_min_weighted_mean,A03_t2_mean_weighted_mean,...,D02_t1_median_weighted_mean_shift,D02_t1_range_weighted_mean_shift,D02_t2_max_weighted_mean_shift,D02_t2_min_weighted_mean_shift,D02_t2_median_weighted_mean_shift,D02_t2_range_weighted_mean_shift,D02_t3_max_weighted_mean_shift,D02_t3_min_weighted_mean_shift,D02_t3_median_weighted_mean_shift,D02_t3_range_weighted_mean_shift
0,2011-01-01,강원,-3.810937,-16.261543,-9.389451,12.450606,6.656067,-3.768142,-14.683870,-8.902063,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2011-01-02,강원,-0.926390,-13.012101,-6.982580,12.085712,6.798315,-0.639606,-13.371353,-7.007748,...,0.032722,0.0,0.032722,0.032722,0.032722,0.000000,0.032722,0.032722,0.032722,0.000000
34,2011-01-03,강원,0.865365,-11.077033,-5.281619,11.942398,7.176418,0.866861,-11.011658,-5.014606,...,0.032722,0.0,0.032722,0.032722,0.032722,0.000000,0.032722,0.032722,0.032722,0.000000
51,2011-01-04,강원,-1.483854,-10.456414,-6.235326,8.972560,3.839204,-1.330371,-10.684152,-6.481597,...,0.032722,0.0,0.032722,0.032722,0.032722,0.000000,0.032722,0.032722,0.032722,0.000000
68,2011-01-05,강원,-4.132359,-13.278535,-8.869313,9.146175,3.197394,-5.179184,-15.398118,-9.817423,...,0.032722,0.0,0.032722,0.032722,0.032722,0.000000,0.098166,0.098166,0.098166,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36346,2016-12-27,강원,-0.446750,-7.214191,-3.356015,6.767440,4.123113,-0.677366,-7.680618,-4.169794,...,0.958688,0.0,1.692067,1.289207,1.490637,0.402860,1.395631,1.233249,1.314440,0.162382
36363,2016-12-28,강원,1.030502,-8.959964,-4.500287,9.990467,3.979500,0.777331,-8.570269,-4.274340,...,1.421172,0.0,1.703714,1.690863,1.697289,0.012851,1.078127,1.012472,1.045299,0.065656
36380,2016-12-29,강원,-2.584927,-10.053244,-5.764153,7.468318,3.019785,-2.787467,-10.288761,-6.121371,...,1.266630,0.0,1.261759,1.045520,1.153639,0.216238,1.831305,1.591707,1.711506,0.239599
36397,2016-12-30,강원,1.116942,-10.171210,-4.041800,11.288152,5.822908,1.128521,-9.959350,-3.289828,...,1.249466,0.0,1.563577,1.336068,1.449823,0.227509,1.719578,1.358635,1.539107,0.360943
36414,2016-12-31,강원,3.791104,-4.186058,-0.812423,7.977161,3.388769,3.592255,-4.028004,-0.652931,...,1.306174,0.0,1.861860,1.701324,1.781592,0.160536,1.443732,1.372693,1.408213,0.071039

In [ ]:
dat2=dat2.fillna(method='bfill')

In [ ]:
dat2.isna().sum()

yyyymmdd                             0
area                                 0
A03_t1_max_weighted_mean             0
A03_t1_min_weighted_mean             0
A03_t1_mean_weighted_mean            0
                                    ..
D02_t2_range_weighted_mean_shift     0
D02_t3_max_weighted_mean_shift       0
D02_t3_min_weighted_mean_shift       0
D02_t3_median_weighted_mean_shift    0
D02_t3_range_weighted_mean_shift     0
Length: 66, dtype: int64

In [ ]:
dat2.to_csv('/content/drive/MyDrive/날씨 빅콘/data/전처리데이터/지수데이터변수추가.csv')